export const TOGGLE_READ = "TOGGLE_READ";

export const TOGGLE_STARRED = "TOGGLE_STARRED";

export const ADD_TO_TRASH = "ADD_TO_TRASH";

export const ADD_TO_SPAM = "ADD_TO_SPAM";

export const SHOW_UNREAD = "SHOW_UNREAD";

export const SHOW_STARRED = "SHOW_STARRED";

export const REMOVE_FROM_SPAM = "REMOVE_FROM_SPAM";

export const ADD_TO_CHECKBOXES = "ADD_TO_CHECKBOXES";

export const REMOVE_FROM_CHECKBOXES = "REMOVE_FROM_CHECKBOXES";